server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:\springcloud\git-local-repo
        #          uri: https://github.com/joneconsulting/spring-cloud-config
#          basedir: /Users/dowonlee/Desktop/Work/tmp/config-repo
#          username: [username]
#          password: [password]
#        native:
#          search-locations: file:///Users/dowonlee/Desktop/Work/native-file-repo
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, busrefresh
